'use strict';

var fs   = require('fs')

module.exports = function (jinn, cb) {
  jinn.log('installing gitignore')

  function copy() {
    var source = fs.createReadStream(__dirname + '/templates/.gitignore')
    var dest   = fs.createWriteStream(process.cwd() + '/' + jinn.appname + '/.gitignore')

    source.on('data', function (chunk) {
      dest.write(chunk)
    })

    source.on('end', function () {
      dest.write('\n')

      if (jinn.options.env) {
        dest.write('# ignore env file\n')
        dest.write('.env\n\n')
      }

      if (jinn.options.coverage) {
        dest.write('# Directory for instrumented libs generated by jscoverage/JSCover\n')
        dest.write('lib-cov\n\n')

        dest.write('# Coverage directory used by tools like istanbul\n')
        dest.write('coverage\n\n')
      }

      dest.end()
    })

    dest.on('finish', cb)
  }

  copy()
}

module.exports.command = {
  flags: '-G, --gitignore',
  description: 'Adds a gitignore file'
}
